name: step4
description: A sample web application
dependencies:
  browser: any
  polymer: '>=0.14.0 <0.15.0'
  core_elements: '>=0.2.0 <0.3.0'
  paper_elements: '>=0.3.0 <0.4.0'
transformers:
- polymer:
    entry_points: web/index.html  